module.exports = {
  ACTIONS: {
    ADD_POINT: 'ADD_POINT',
    ADD_LINE: 'ADD_LINE',
    REMOVE_POINT: 'REMOVE_POINT',
    ADD_GRAPH: 'ADD_GRAPH',
    REMOVE_GRAPH: 'REMOVE_GRAPH',
    SET_GRAPH_PROPERTIES: 'SET_GRAPH_PROPERTIES',
    SELECT_GRAPH: 'SELECT_GRAPH',
    SELECT_LINE: 'SELECT_LINE',
    PROCESS_GRAPH: 'PROCESS_GRAPH',
    PROCESS_GRAPH_COMPLETE: 'PROCESS_GRAPH_COMPLETE',
    SET_GRAPH_HISTORY_OPEN_STATE: 'SET_GRAPH_HISTORY_OPEN_STATE'
  }
};