module.exports = {
  ACTIONS: {
    ADD_POINT: 'ADD_POINT',
    ADD_LINE: 'ADD_LINE',
    REMOVE_POINT: 'REMOVE_POINT',
    ADD_GRAPH: 'ADD_GRAPH',
    REMOVE_GRAPH: 'REMOVE_GRAPH',
    SELECT_GRAPH: 'SELECT_GRAPH',
    SELECT_LINE: 'SELECT_LINE',
    PROCESS_GRAPH: 'PROCESS_GRAPH',
    PROCESS_GRAPH_COMPLETE: 'PROCESS_GRAPH_COMPLETE'
  },
  DIMENSIONS: {
    CIRCLE_RADIUS: 10,
    GRAPH_WIDTH: 400,
    GRAPH_HEIGHT: 400
  }
};